version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: QQWWEE123
      MYSQL_DATABASE: code
      MYSQL_USER: usnik
      MYSQL_PASSWORD: qwe123
  web:
    build: .
    ports:
      - 80:5000
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DB_HOST: db
      DB_NAME: code
      DB_USER: usnik
      DB_PASSWORD: qwe123
    depends_on:
      - db
